# Change these first
owner: PengiOS # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Pengi OS Website
    url: https://pengios.github.io
  - name: Pengi OS Homepage
    url: https://pengios.github.io/homepage
  - name: Pengi OS Wiki
    url: Https://pengios.github.io/wiki
  - name: Pengi OS Forums
    url: https://github.com/PengiOS/Forums/discussions
  - name: Pengi Status
    url: https://pengios.github.io/status

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: pengios.github.io
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/PengiOS/pengios.github.io/main/homepage/assets/icon.png
  name: Status - PengiOS
  favicon: https://raw.githubusercontent.com/PengiOS/pengios.github.io/main/homepage/assets/icon.png
  introTitle: "**PengiStatus** is our status tracker to publish uptime and record outages."
  introMessage: It uses GitHub Actions to track our services every 10 minutes. If you'd like to see more details, contact us or [make an issue on our GitHub](https://github.com/PengiOS/status).
  navbar:
    - title: Status
      href: /status
    - title: Main Site
      href: https://pengios.github.io/
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
